import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-auto px-5 md:px-14 lg:max-w-6xl bg-[#3F1651] text-slate-400'>
          <h1>Header</h1>
          {children}
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  )
}
