import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LargeLogo from '@/components/logo/LargeLogo'
import MiniLogo from '@/components/logo/MiniLogo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='py-6 border-b-[1px] mb-10'>
          <div className='hidden lg:block'>
            <LargeLogo />
          </div>
          <div className='block lg:hidden'>
            <MiniLogo />
          </div>
        </div>
        <div className='mx-auto px-5 md:px-14 lg:max-w-6xl'>
          {children}
        </div>
        <div className='py-6'>
          <p>rizqyhbb@gmail.com</p>
        </div>
      </body>
    </html>
  )
}
