import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-auto px-5 md:px-14 lg:max-w-6xl bg-[#3F1651] text-slate-400'>
          <div className='py-6'>
            <Link href={'/'}>
              <h1>Kiki&apos;s blog</h1>
            </Link>
          </div>
          {children}
          <div className='py-6'>
            <p>rizqyhbb@gmail.com</p>
          </div>
        </div>
      </body>
    </html>
  )
}
